"""make email unique

Revision ID: 043d5aab164d
Revises: 56f802d465e2
Create Date: 2024-09-12 19:36:48.404680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043d5aab164d'
down_revision: Union[str, None] = '56f802d465e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promotion', 'discount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1, asdecimal=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('promotion', 'discount',
               existing_type=sa.Float(precision=1, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
