"""create course bought table

Revision ID: 4910af0e2165
Revises: 67b38ca13f13
Create Date: 2024-09-21 15:35:36.819099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4910af0e2165'
down_revision: Union[str, None] = '67b38ca13f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_bought',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('payed', sa.Integer(), nullable=False),
    sa.Column('time_bought', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_bought')
    # ### end Alembic commands ###
